### ISSUE TITLE
LivingEntityMixin.java setting incorrect step height for nonPlayers

### ISSUE THREAD

**Issue by witsar** [RobertHoueland/enchantments-plus#11]
Your Hiker enchant is causing issues with vehicles (such as Horses) by arbitarily setting currentEntity.setStepHeight(0.6F); in LivingEntityMixin.java. You can simply remove the _else_ case to fix this bug.

**Comment by RobertHoueland** [comment]
I took a look at this a while back and thought I reproduced it but now I can't seem to. What version is this on?
I tried equipping hiker and unequipped the boots and the horse functioned normally.

For now, I changed the else case to `else if (currentEntity instanceof PlayerEntity)` in the latest version [v1.2.1](https://github.com/RobertHoueland/enchantments-plus/releases/tag/1.2.1) for Minecraft versions 1.20.1 and 1.20.2

Let me know if that solves it for you!

**Comment by witsar** [comment]
That was for the 1.19.2 version (https://github.com/RobertHoueland/enchantments-plus/blob/1.19.2/src/main/java/com/robdog777/enchantmentsplus/mixin/LivingEntityMixin.java), but i think 1.20 had the same issue. I fixed this locally on my side back then but thought i would let you know of this bug as well. Checking for PlayerEntity indeed solves this, thanks for taking care. Cheers

**Comment by witsar** [comment]
That was for the 1.19.2 version (https://github.com/RobertHoueland/enchantments-plus/blob/1.19.2/src/main/java/com/robdog777/enchantmentsplus/mixin/LivingEntityMixin.java), but i think 1.20 had the same issue. I fixed this locally on my side back then but thought i would let you know of this bug as well. Checking for PlayerEntity indeed solves this, thanks for taking care. Cheers
