### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by kualatoni** [RobertHoueland/enchantments-plus#14]
I recently installed a library for another mod I wanted to download, but it crashed my game whenever I started it up. I opened an issue with the mod author and he said "the reach-entity-attributes library [you] are using is broken" and that what was causing problems. Can you look into this? I've attached my most recent crash report if it helps.

[crash-2024-02-15_22.32.26-client.txt](https://github.com/RobertHoueland/enchantments-plus/files/14314776/crash-2024-02-15_22.32.26-client.txt)

**Comment by RobertHoueland** [comment]
An update for reach entity attributes just got released today for MC 1.20.4, so I will update enchantments-plus soon and hopefully that will fix your crash

**Comment by kualatoni** [comment]
Thankfully your library is no longer causing problems, although now another one is. Thanks for the help tho.
