### ISSUE TITLE
[Suggestion] Make the Raider enchantment deal extra damage to ALL raid mobs (vexes, witches, ravagers)

### ISSUE THREAD

**Issue by StressedCatInABox** [RobertHoueland/enchantments-plus#18]
Despite the name and enchant description, the Raider enchantment only deals extra damage to Illagers, not raid mobs. This group includes Pillagers, Vindicators and Evokers ONLY. I think it would be cool if it did damage to ALL the raid mobs, and not just illagers. Alternatively, make it obvious that it's only for illagers, and not the rest. (But I don't think that would be a neat change)

I'm not quite sure how this would look code wise, but I BELIEVE it should be relatively simple to implement?

**Comment by RobertHoueland** [comment]
Thank you for the suggestion! Apologies for the late response, but I'll be implementing this in the next release
