### ISSUE TITLE
conflict with StepUpNext mod

### ISSUE THREAD

**Issue by dadoirie** [RobertHoueland/enchantments-plus#2]
nullifies mod [StepUpNext](https://www.curseforge.com/minecraft/mc-mods/stepupnext) ... most likely because of the hiker enchantment ... can that enchantment excluded somehow and also removing that conflict?

EDIT: since its MIT licensed I've removed all related hiker code (before the 1.129 and double leap commit since that enchantment and mc version also not really needing) and rebuild it till a proper update is being released

**Comment by RobertHoueland** [comment]
Hi, thanks for letting me know. I'm currently working on adding a config file to the mod, to disable enchantments individually, which should fix the conflict.

**Comment by RobertHoueland** [comment]
I've added support for cloth config API, so you can disable enchantments of your choosing. Works with Mod Menu too in v1.1.3
