### ISSUE TITLE
Incompatible with 1.20.6

### ISSUE THREAD

**Issue by spaceclouds42** [RobertHoueland/enchantments-plus#21]
Hey, this doesn't really seem like the best place to put this since your code repo and CurseForge posting don't indicate 1.20.6 support, but I couldn't find a better way to contact you so I suppose an issue will do. 

On Modrinth, it is listed as having support for 1.20.4, .5, and .6, however on 1.20.6, the following [mixin](https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/1.20.4/src/main/java/com/jamieswhiteshirt/reachentityattributes/mixin/InventoryValidationMixin.java) fails:
```
mixins.reach-entity-attributes.json:InventoryValidationMixin -> net.minecraft.class_1263
```
Full [crash report](https://mclo.gs/KEHctg7) when running just this mod w/dependencies

This is from the [reach-entity-attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes) dependency that your mod uses, which has not yet been updated to 1.20.6

I'll also open an issue on their project and see if I have the time/patience to set up my modding workspace to submit a PR to port it to 1.20.6, but in the meantime, if you could remove the 1.20.6 support indicator on Modrinth, that'd be cool, thanks!

**Comment by RobertHoueland** [comment]
The mod isn't updated yet for those versions. I'm working on a 1.20.6 update at the moment. I incorrectly labeled it on Modrinth as compatible with those other versions, thank you for letting me know
