### ISSUE TITLE
Excavator not obtainable from enchanting table?

### ISSUE THREAD

**Issue by RedPandaBro** [RobertHoueland/enchantments-plus#5]
I noticed while trying to max out my pick axe that I had not once seen the enchant. I tried it in creative and still couldn't get the enchant. Wasn't sure if it was meant to be loot only so I'll leave this message here.

**Comment by RobertHoueland** [comment]
Hi, are you on mod version v1.1.7 for Minecraft version 1.20? If so, then update to the latest mod version as Excavator doesn't work properly in 1.1.7. 
Otherwise, it shouldn't be a treasure enchantment so I will look into it when I can.

**Comment by RedPandaBro** [comment]
I just checked. I am using version 1.1.8 because me and my mates are playing on a 1.20.1 server. I know the enchantment works to increase reach however, I don't think I can get it from an enchanting table. We enjoy using your mod. Thank you for looking into it!

**Comment by RobertHoueland** [comment]
I just made a change to the level required for the enchantment, and tested it and I was able to find Excavator in the enchantment table. The change is active in [v1.1.9](https://github.com/RobertHoueland/enchantments-plus/releases/tag/1.1.9)
Let me know if you can find it now! (it's still fairly rare)
