### ISSUE TITLE
Depend only version 11.0.99 of cloth-config

### ISSUE THREAD

**Issue by Minecrafthyr** [RobertHoueland/enchantments-plus#6]
fabric.mod.json

Line 37:
```json
    "cloth-config": "11.0.99"
```

It should be:
```json
    "cloth-config": ">11.0.99"
```

**Comment by RobertHoueland** [comment]
Good catch, thank you! Fixed in [v1.1.10](https://github.com/RobertHoueland/enchantments-plus/releases/tag/1.1.10)
