### ISSUE TITLE
Excavator enchant not working

### ISSUE THREAD

**Issue by Cone344** [RobertHoueland/enchantments-plus#7]
Just added excavator III to a netherite pick and it doesn't increase reach whatsoever. Am I missing something?

**Comment by RobertHoueland** [comment]
What version are you using? If you're on mod v1.1.7 for Minecraft version 1.20, then it's known that Excavator doesn't work properly on that version (the dependency hadn't been updated at the time but I still wanted to push out an update). So in that case update to the latest version, where Excavator does work when you're holding the pickaxe.

**Comment by Cone344** [comment]
I am on version 1.1.10 for minecraft 1.20.1, all other enchantments work properly. I even upgraded to mod version 1.1.11 but to no avail.

**Comment by RobertHoueland** [comment]
What specific tool are you using (Diamond Pickaxe?) and what other enchantments are you using on the tool? Thank you!

**Comment by Cone344** [comment]
Hi again, I am using a netherite pickaxe. On the pickaxe itself i only have excavator 3 and nothing else, but I do have life steal 3 on my sword and it works. I am on singleplayer.

**Comment by Cone344** [comment]
Nevermind! Did a new minecraft installation and reinstalled the mod and it works now.

**Comment by RobertHoueland** [comment]
Great! It might have been something off with the config since I had to disable the enchantment in one version and then reenable it. Glad it's working
