### ISSUE TITLE
Edited config and kept crashing

### ISSUE THREAD

**Issue by neptunespearz** [RobertHoueland/enchantments-plus#8]
Disabled the double leap enchant in config using mod menu and it kept crashing my worlds after I reloaded. Enabled it back and it stopped crashing.

**Comment by RobertHoueland** [comment]
Pushed a fix for this in [v1.1.12](https://github.com/RobertHoueland/enchantments-plus/releases/tag/1.1.12) where I worked to redo how enchantments are disabled. Can you update to this latest version and let me know if the crashing is resolved?

With these changes, if there are items in a world with a disabled enchantment, the item will still display the enchantment on it, but there will be no effect from it.

**Comment by neptunespearz** [comment]
fixed, thankyou! backport of configs to 1.19.2 would be nice if you have time :)

**Comment by RobertHoueland** [comment]
Sure, Minecraft 1.19.2 is a popular version for modding and I've made quite a few changes on the mod since then so it's definitely worth back porting.

[Try it out!](https://github.com/RobertHoueland/enchantments-plus/releases/tag/1.1.13%2B1.19.2)

**Comment by neptunespearz** [comment]
you're amazing
